### PR TITLE
Move files into more sensible place and BOM

### PR DESCRIPTION
**Pull request by darraghbr**

### CODE REVIEW

**Comment by capsulecorplab** [comment]
This seems more like a purchase order (PO) than a BOM. That being said, should this repo include P/N's that aren't in-house design (STL) files?

**Comment by darraghbr** [comment]
> 
> 
> This seems more like a purchase order (PO) than a BOM. That being said, should this repo include P/N's that aren't in-house design (STL) files?

It currently has both in house part numbers and part numbers that are external, I didn't realise I hadn't left this as draft as I'm not done with the BOM, there are still more of the in house part numbers to be added. 

The external part numbers are really there as a reference to back up the functional description of the component in case the description needs to be clarified, the cost isn't especially relevant but there we are.

**Comment by darraghbr** [comment]
NB the links in the BOM to the internal parts won't work currently but once this gets merged into main they should work properly.

**Review by Judoguy12 — APPROVED** [review]
lgtm

**Comment by capsulecorplab** [comment]
I think this will eventually need to go into the tetra (docs) repo, as per https://github.com/tetrabiodistributed/tetra/issues/121

**Comment by darraghbr** [comment]
Yes that is the more sensible place to put the BOM. I will look into that.

**Comment by darraghbr** [comment]
> 
> 
> lgtm

What's the silicon flappy bit called, have we got a source for them? Also not sure if I should break out the components from the pressure manifold, the o-ring and the M5 studs? What else is the BOM missing?

**Comment by Judoguy12** [comment]
Check Valve disks

https://www.amazon.co.uk/Trimming-Shop-Breathing-Accessories-Protection/dp/B08F2JQKSX/ref=sr_1_8?dchild=1&keywords=Face+Cover+Valves&qid=1608139872&sr=8-8

**Comment by Judoguy12** [comment]
Yeah Oring and M5 should be included

**Review by Judoguy12 — APPROVED** [review]
Looks like its all there

**Comment by mmroden** [comment]
LGTM, reviewed in the zoom

**Pull request merged**
