### PR TITLE
Next revision of PCB

### PR DESCRIPTION
**Pull request by darraghbr**
Changed I2C pullup resistors to 3Kohm

General tidy up and fix of issues on the PCB. Tweaked some polygons to eliminate sharp corners, made some traces larger. Eliminated some clearance issues.

I have used the JLCPCB official DRU and CAM processing file, both have been included with the PR.

I have not edited the version number on the board itself as I don't know what type of versioning you are using.

### CODE REVIEW

**Comment by mechatroniks-git** [comment]
Schematic  review: 
- I'd request that all schematic changes (3K resistors, date & anything else that changed) get noted in upper left hand corner
image

Board Review: 
- Date on the silk should be updated
image
- Using this DRU: https://github.com/JLCPCBofficial/jlcpcb-eagle/tree/master/design%20rules and changing the value in  Clearance Tab - Same Signals - SMD to Via = 0. DRC Passed. 
`mdSmdVia = 0mil`

BOM:
[BOM](https://github.com/darraghbr/project-tetra/blob/master/02_Development/FlowMeter/RPi%20Board/BOM%20and%20Parts%20Layout/RPI_v004_BOM.csv) needs to be changed to reflect the [3K resistors](https://lcsc.com/product-detail/Chip-Resistor-Surface-Mount_UNI-ROYAL-Uniroyal-Elec-0805W8F3001T5E_C17661.html)

CPL:
If any SMT component placement locations have changed, then the [CPL](https://github.com/darraghbr/project-tetra/blob/master/02_Development/FlowMeter/RPi%20Board/BOM%20and%20Parts%20Layout/raspberry_pi_v004_CPL.csv) file needs to be updated, ignore otherwise.

**Review by mechatroniks-git — CHANGES_REQUESTED** [review]
See prior comment

**Review by mechatroniks-git — APPROVED** [review]
Looks good. Date format on silk changed to the non-US format (day/month/year), which should be ok.

**Comment by darraghbr** [comment]
Added a cautionary text file to explain the issue with the automatically generated BOM using the incorrect resistor values, as discussed in todays meeting.

**Review by mechatroniks-git — APPROVED** [review]

**Pull request merged**
