### PR TITLE
sensor board updates

### PR DESCRIPTION
**Pull request by mechatroniks-git**

### CODE REVIEW

**Comment by hydronics2** [comment]
there's a couple overlap issues on the bottom side of the board. 
image

**Comment by darraghbr** [comment]
If the GND trace is rerouted to something like this we should be good to go, I would commit this change but I don't have permissions.

image

**Comment by mechatroniks-git** [comment]
That's wierd, its passed checks, then I realized the PCB was located out in space, so I moved it to 0,0 in 2 steps, didn't think tracks would shift. It's fixed now @hydronics2 
image

**Review by darraghbr — APPROVED** [review]
All looks good, no issues that I can spot.

**Comment by mechatroniks-git** [comment]
I grew the outline so it meets the 20mm x 20mm minimum for JLC Assembly

**Comment by darraghbr** [comment]
Reviewed changes, all looks good. Ready for merge.

**Pull request merged**
