### PR TITLE
Pi Hat Adjustments

### PR DESCRIPTION
**Pull request by mechatroniks-git**
This PR is adding in the latest files, and the files used to do the board build. Still need DRC check, BOM and CPL file generation.

### CODE REVIEW

**Comment by darraghbr** [comment]
I believe there is a comment on the schematic about a logic level conversion? But looking at the datasheet for the chips I can't see anything about it.

**Comment by darraghbr** [comment]
Is that note more about the sensors themselves communicating at 5V? (Which is weird I thought all I2C stuff talked at 0.7VDD for the high signal)

**Review by darraghbr — CHANGES_REQUESTED** [review]
There are a few traces that could do with mitering. and the DRC check reports a single trace stub, neither are critical.

I believe we are double accounting for the pull up resistors on the I2C bus. We have some pull ups on the main board and some on this daughter board, we should have either or. 

If we can add the other half of the I2C buffer onto the main board we should. A customer may use a significantly longer cable than we advise and it would cause issues without the buffers

The note on the schematic about level shifting should be removed, the I2C multiplexers level shift everything from 5V to 3.3V for the pi.

**Comment by hydronics2** [comment]
The comment about logic level conversion is related to the P82B715 extender chip. If we're not using that extender chip you can ignore the comment.

**Comment by mechatroniks-git** [comment]
@darraghbr, if you get time, please review the schematic changes. Board file is not attached, as I'm still tweaking the layout. Thanks.

https://github.com/tetrabiodistributed/project-tetra/commit/3873a2f7b77e5f8129a385210406294016aba3f5

**Comment by darraghbr** [comment]
Hi Patrick, it seems the current Pi board does not pass the DRC check that was committed, there is a single clearance issue and some keepout flags between some of the caps and resistors that I'm not quite convinced are really an issue. There is a couple of kinky traces that could be smoothed out, but nothing critical.

**Comment by mechatroniks-git** [comment]
@darraghbr v007 should be much better

**Review by darraghbr — CHANGES_REQUESTED** [review]
That's looking much better, can you just have a little tidy up of this commit? If we could rename this PR to pi hat adjustments and then do another PR for the sensirion board? By my count there should just be the 3 Pi board files in this PR, up to you if you want to throw the gerbers and DRU files in here too.

**Comment by mechatroniks-git** [comment]
Last tweaks to the documentation, added the missing files (DRU, gerber zip, BOM & CPL)

**Comment by mechatroniks-git** [comment]
@hydronics2 would you mind reviewing the v007 of the pi board?

**Comment by hydronics2** [comment]
Absolutely. Will do this evening.

**Comment by hydronics2** [comment]
Oh my... I've never seen so many pullup resistors on a PCB!

- nice job squeezing those i2c bus extenders onto the board
- The sensirion connector board should have the same value i2c pullups on each side of the i2c bus extender (P82B715)... It looks like it's 470ohm on RPI board (matches the cut sheet) and I used 330ohm on the last connector board. Just something to confirm.
image
- the routing and ground planes look much improved
- I haven't had a lot of experience placing fiducial markers so I cant comment on them
- silk screen looks good with labels and values
- do you still like this method for jumping the 5V power? Seemed like it worked great for prototyping but might make more sense to use a small jumper that's 'made' during reflow.... more of a production model?
image
- all ICs appear to have a ground connection and power connection

**Comment by mechatroniks-git** [comment]
Thanks @hydronics2, we can leave the 5V jumper and install a zero-ohm.

You are looking at an older version of the Sensirion board, you can find it here: https://github.com/tetrabiodistributed/project-tetra/tree/Sensirion-control-PCB-adjustments-%23113/02_Development/FlowMeter/sensirion_connector_pcb/eagle

**Comment by hydronics2** [comment]
@mechatroniks-git ok sorry about that. for some reason the #155 didn't include the up to date sensirion PCB but I see it's on the main branch. 

If we use a zero-ohm resistor, just have to make sure it's big enough. It looks like 1206 is probably fine for this Vishay series. I think we were targeting 3amp constant current supply.  https://www.vishay.com/docs/31017/rcwp99.pdf
image

**Comment by mechatroniks-git** [comment]
@hydronics2 @darraghbr 
I've updated the files, looking for someone to review

**Comment by darraghbr** [comment]
> @hydronics2 @darraghbr
> I've updated the files, looking for someone to review

Hi Patrick, I believe we agreed to keep this PR to just the Pi Hat changes? I can still see a lot of file changes that look like they are related to the Sensirion board?

**Comment by mechatroniks-git** [comment]
@darraghbr I created 2 new PRs to split them up as requested, closing this one

**Pull request closed without merging**
