### PR TITLE
updated PCB with new 5V regulator

### PR DESCRIPTION
**Pull request by hydronics2**
added new 5V regulator as existing regulator was out-of-stock at JLCPCB

### CODE REVIEW

**Comment by mechatroniks-git** [comment]
Everything looks good. Perhaps consider replacing C22/C25 with this guy: https://lcsc.com/product-detail/Multilayer-Ceramic-Capacitors-MLCC-SMD-SMT_Samsung-Electro-Mechanics-CL31A226KPHNNNE_C5672.html This better matches the voltage rating and size they used in the datasheet. I can't find any reason the ones you selected wouldn't work, but they ask for a 2mohm low ESR cap, but can't find that info on the datasheet.

**Comment by hydronics2** [comment]
Ok, sounds good. I updated the capacitor.

**Review by mechatroniks-git — APPROVED** [review]
Changes look good.

**Comment by Burhan-Q** [comment]
@hydronics2 and @mechatroniks-git merging changes

**Pull request merged**
